### PR TITLE
new shell script submit job

### PR DESCRIPTION
**Pull request by aviVzm05**
Signed-off-by: avinash <avi.vzm05@gmail.com>
New shell script created to  submit an existing job from mainframe PDS, wait  for it's output and based on success/failure of the same download  the job logs.

### CODE REVIEW

**Comment by zFernand0** [comment]
LGTM!
Might be related to [shell/parse_job.sh](https://github.com/zowe/zowe-cli-sample-scripts/blob/master/shell/parse_job.sh)?

Also, it'd be nice if there was a small README in each folder (e.g. `shell`, `python`, `use_cases`) similar to the `cics` folder. This will hopefully avoid having any sort of duplication. 😋

**Comment by aviVzm05** [comment]
@zFernand0 , kind of smilar to that, just didn't knew that before and trying to learn the cli by using them :) hope  it is okay...
added Readme to this folder...

**Review by zFernand0 — APPROVED** [review]
Thanks for doing it! 😋

**Comment by zFernand0** [comment]
We can pull someone from the Docs Squad later one and figure out what will be the best thing to do in terms of a quick summary of the examples in each `folder`/README.md

**Pull request merged**
