### PR TITLE
Sonarqube2

### PR DESCRIPTION
**Pull request by tucker01**
This PR introduces a sample project for analyzing source code contained in datasets with sonarqube.

### CODE REVIEW

**Comment by MikeBauerCA** [comment]
Nicely done. Perhaps on the README at the root of the repository, for the SonarQube Data Set Analysis use case link to https://github.com/zowe/zowe-cli-sample-scripts/tree/sonarqube2/use_cases/sonarqube_datasets instead of https://github.com/zowe/zowe-cli-sample-scripts/blob/sonarqube2/use_cases/sonarqube_datasets/README.md.

**Comment by tucker01** [comment]
Is there a way to make that "relative"? Or would I have to hard-code the master branch tree?

**Comment by zFernand0** [comment]
> Is there a way to make that "relative"? Or would I have to hard-code the master branch tree?

Yeah, you can make it relative. `./usecases/sonnarqube_datasets/`

**Comment by tucker01** [comment]
OK thanks, I normally don't do that because it doesn't work (at least in vscode) when you have the project locally, but I Mike's suggestion makes sense here.

**Pull request merged**
