### PR TITLE
Committed Twilio sample script for CA ESP

### PR DESCRIPTION
**Pull request by gcartier94**
This is a sample script using the Twilio service to send an SMS and Zowe CLI to perform infrastructure tasks on CA ESP. This script is part of the presentation done on SHARE in Pittsburgh on Aug 8 2019 (Session ID 25235).

### CODE REVIEW

**Comment by MarkAckert** [comment]
Thanks for the contribution! If possible, could you add the SPDX License header to your source files?

@zFernand0 It looks like some older sources are missing the header, what do you think about adding updateLicense to this repository with modified matcher patterns? https://github.com/zowe/zowe-cli-db2-plugin/blob/master/scripts/updateLicense.js

**Comment by gcartier94** [comment]
> Thanks for the contribution! If possible, could you add the SPDX License header to your source files?
> @zFernand0 It looks like some older sources are missing the header, what do you think about adding updateLicense to this repository with modified matcher patterns? https://github.com/zowe/zowe-cli-db2-plugin/blob/master/scripts/updateLicense.js

Thank you for the quick update Mark, just included the License header on my source files, please let me know in case you need anything else :)

**Comment by zFernand0** [comment]
I sure can! 👍 
I will open a separate PR, and include the updateLicense as part of the npm scripts.
Thanks for mentioning 😄

**Comment by zFernand0** [comment]
@MarkAckert
PR #15 is out there for this same purpose. 🥂

**Pull request merged**
